/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javazoom.jlgui.basicplayer.BasicPlayerException;
import org.jaudiotagger.audio.exceptions.CannotReadException;
import org.jaudiotagger.audio.exceptions.InvalidAudioFrameException;
import org.jaudiotagger.audio.exceptions.ReadOnlyFileException;
import org.jaudiotagger.tag.TagException;
import reproductormp3.ReproductorMp3;

public class Pantalla2 extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla2
     */
    public static DefaultListModel listaTodo;
    public static DefaultListModel listaNueva;
    
    public Pantalla2() throws CannotReadException, IOException, TagException, ReadOnlyFileException, InvalidAudioFrameException, BasicPlayerException {
        initComponents();
        listaTodo=new DefaultListModel();
        jListTodo.setModel(listaTodo);
        
        listaNueva=new DefaultListModel();
        jListNuevaLista.setModel(listaNueva);
        
        //ReproductorMp3.ListaCanciones.ObtenerDatos2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgregar = new javax.swing.JLabel();
        lblGuardar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        txtNombreList = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTodo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNuevaLista = new javax.swing.JList<>();
        lblPantalla2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblAgregar);
        lblAgregar.setBounds(30, 480, 140, 50);

        lblGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblGuardar);
        lblGuardar.setBounds(190, 480, 150, 50);

        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblCerrar);
        lblCerrar.setBounds(320, 10, 30, 30);

        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblMinimizar);
        lblMinimizar.setBounds(270, 10, 30, 30);

        txtNombreList.setBackground(new java.awt.Color(240, 240, 240));
        txtNombreList.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtNombreList.setText("Lista nueva de reproducción");
        txtNombreList.setToolTipText("");
        txtNombreList.setBorder(null);
        txtNombreList.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreListActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreList);
        txtNombreList.setBounds(70, 90, 230, 20);

        jListTodo.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jListTodo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 140, 260);

        jListNuevaLista.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jListNuevaLista);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 180, 150, 260);

        lblPantalla2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Recurso 8.png"))); // NOI18N
        lblPantalla2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblPantalla2MouseDragged(evt);
            }
        });
        lblPantalla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPantalla2MousePressed(evt);
            }
        });
        getContentPane().add(lblPantalla2);
        lblPantalla2.setBounds(0, 0, 370, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void lblPantalla2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPantalla2MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_lblPantalla2MousePressed

    private void lblPantalla2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPantalla2MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_lblPantalla2MouseDragged

    private void txtNombreListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pantalla2().setVisible(true);
                } catch (CannotReadException ex) {
                    Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (TagException ex) {
                    Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ReadOnlyFileException ex) {
                    Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvalidAudioFrameException ex) {
                    Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (BasicPlayerException ex) {
                    Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> jListNuevaLista;
    public javax.swing.JList<String> jListTodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblAgregar;
    public javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblGuardar;
    public javax.swing.JLabel lblMinimizar;
    public javax.swing.JLabel lblPantalla2;
    public javax.swing.JTextField txtNombreList;
    // End of variables declaration//GEN-END:variables
}
