/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javazoom.jlgui.basicplayer.BasicPlayerException;
import org.jaudiotagger.audio.AudioFile;
import org.jaudiotagger.audio.AudioFileIO;
import org.jaudiotagger.audio.exceptions.CannotReadException;
import org.jaudiotagger.audio.exceptions.InvalidAudioFrameException;
import org.jaudiotagger.audio.exceptions.ReadOnlyFileException;
import org.jaudiotagger.tag.FieldKey;
import org.jaudiotagger.tag.TagException;
import reproductormp3.Cancion;
import reproductormp3.List;
import reproductormp3.ListaReproduccion;
import reproductormp3.Nodo;
import reproductormp3.ReproductorMp3;
import Controladores.ControlarP1;

public class Pantalla1 extends javax.swing.JFrame {

    public static DefaultListModel listaM;
    public static DefaultListModel listaR=new DefaultListModel();
    
    /**
     * Creates new form Pantalla1
     */
    public Pantalla1() throws CannotReadException, IOException, TagException, ReadOnlyFileException, InvalidAudioFrameException {
        initComponents();
        listaM=new DefaultListModel();
        jListCanciones.setModel(listaM);
        
        listaR=new DefaultListModel();
        jListRep.setModel(listaR);
        jListRep.setSelectedIndex(0);
        AgregarLista();
        
        lblPorVol.setText(jVolumen.getValue()+" %");
    }
    
    public void AgregarLista() throws CannotReadException, IOException, TagException, ReadOnlyFileException, InvalidAudioFrameException{
        /*File f = new File("C:\\Users\\JERSON SALAZAR\\Documents\\NetBeansProjects\\Proyecto Reproductor Mp3\\ReproductorMp3\\Canciones");
        File[] lista=f.listFiles();
        String a;
        for(int i =0; i<lista.length;i++){
            a=lista[i].getPath();
            AudioFile audio = AudioFileIO.read(lista[i]);
            org.jaudiotagger.tag.Tag tag = audio.getTag();
            FieldKey[] parametro = {FieldKey.ALBUM,  FieldKey.ARTIST, FieldKey.YEAR, 
                FieldKey.GENRE, FieldKey.TITLE, FieldKey.TRACK,FieldKey.AMAZON_ID 
            };    
            listaM.addElement(tag.getFirst(FieldKey.TITLE));
        }*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblPlay = new javax.swing.JLabel();
        lblStop = new javax.swing.JLabel();
        lblPause = new javax.swing.JLabel();
        lblSiguiente = new javax.swing.JLabel();
        lblAnterior = new javax.swing.JLabel();
        jVolumen = new javax.swing.JSlider();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblPorVol = new javax.swing.JLabel();
        lblAgregarLista = new javax.swing.JLabel();
        lblOrdenarAZ = new javax.swing.JLabel();
        lblRepetir = new javax.swing.JLabel();
        lblSeleccionar = new javax.swing.JLabel();
        lblBorrarCancion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCanciones = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRep = new javax.swing.JList<>();
        lblOrdenarZA = new javax.swing.JLabel();
        lblCancionSonando = new javax.swing.JLabel();
        lblListRSonando = new javax.swing.JLabel();
        lblPantalla1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblMinimizar);
        lblMinimizar.setBounds(810, 4, 30, 30);

        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblCerrar);
        lblCerrar.setBounds(854, 4, 40, 30);

        lblPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblPlay);
        lblPlay.setBounds(300, 460, 70, 70);

        lblStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblStop);
        lblStop.setBounds(510, 460, 70, 70);

        lblPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblPause);
        lblPause.setBounds(410, 460, 70, 70);

        lblSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblSiguiente);
        lblSiguiente.setBounds(620, 460, 60, 60);

        lblAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblAnterior);
        lblAnterior.setBounds(210, 460, 60, 60);

        jVolumen.setForeground(new java.awt.Color(9, 7, 9));
        jVolumen.setMajorTickSpacing(5);
        jVolumen.setValue(80);
        jVolumen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jVolumenStateChanged(evt);
            }
        });
        getContentPane().add(jVolumen);
        jVolumen.setBounds(10, 480, 90, 20);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(0, 440, 910, 14);

        lblPorVol.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblPorVol.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPorVol);
        lblPorVol.setBounds(30, 500, 60, 20);

        lblAgregarLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblAgregarLista);
        lblAgregarLista.setBounds(820, 460, 60, 80);

        lblOrdenarAZ.setBackground(new java.awt.Color(255, 255, 255));
        lblOrdenarAZ.setForeground(new java.awt.Color(255, 255, 255));
        lblOrdenarAZ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblOrdenarAZ);
        lblOrdenarAZ.setBounds(273, 70, 20, 20);

        lblRepetir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblRepetir);
        lblRepetir.setBounds(124, 470, 40, 40);

        lblSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionar.setText("Select");
        lblSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblSeleccionar);
        lblSeleccionar.setBounds(840, 414, 50, 20);

        lblBorrarCancion.setForeground(new java.awt.Color(255, 255, 255));
        lblBorrarCancion.setText("Borrar");
        getContentPane().add(lblBorrarCancion);
        lblBorrarCancion.setBounds(610, 410, 40, 30);

        jListCanciones.setBackground(new java.awt.Color(9, 7, 9));
        jListCanciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jListCanciones.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jListCanciones.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jListCanciones);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 630, 270);

        jScrollPane2.setBackground(new java.awt.Color(9, 7, 9));
        jScrollPane2.setForeground(new java.awt.Color(240, 240, 240));

        jListRep.setBackground(new java.awt.Color(9, 7, 9));
        jListRep.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jListRep.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jListRep);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(680, 130, 220, 270);

        lblOrdenarZA.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblOrdenarZA.setForeground(new java.awt.Color(255, 255, 255));
        lblOrdenarZA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblOrdenarZA);
        lblOrdenarZA.setBounds(273, 95, 20, 20);

        lblCancionSonando.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblCancionSonando.setForeground(new java.awt.Color(240, 240, 240));
        lblCancionSonando.setText("........");
        getContentPane().add(lblCancionSonando);
        lblCancionSonando.setBounds(20, 410, 760, 20);

        lblListRSonando.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblListRSonando.setForeground(new java.awt.Color(255, 255, 255));
        lblListRSonando.setText(".....");
        getContentPane().add(lblListRSonando);
        lblListRSonando.setBounds(420, 44, 220, 30);

        lblPantalla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Recurso 7.png"))); // NOI18N
        lblPantalla1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblPantalla1MouseDragged(evt);
            }
        });
        lblPantalla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPantalla1MousePressed(evt);
            }
        });
        getContentPane().add(lblPantalla1);
        lblPantalla1.setBounds(0, -10, 920, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void lblPantalla1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPantalla1MousePressed
        xx=evt.getX();
        xy=evt.getY();    
    }//GEN-LAST:event_lblPantalla1MousePressed

    private void lblPantalla1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPantalla1MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_lblPantalla1MouseDragged

    
    public static double getVolu(){
        return volFinal;
    }
    
    public static double volFinal=0.8;
    
    private void jVolumenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jVolumenStateChanged
        // TODO add your handling code here:
        volFinal=jVolumen.getValue()/100.0;
        lblPorVol.setText(jVolumen.getValue()+" %");
        try {
            ReproductorMp3.ListaRepro.MandarVolumen(jListRep.getSelectedIndex(), volFinal);
        } catch (BasicPlayerException ex) {
            Logger.getLogger(Pantalla1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jVolumenStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pantalla1().setVisible(true);
                } catch (CannotReadException ex) {
                    Logger.getLogger(Pantalla1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Pantalla1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (TagException ex) {
                    Logger.getLogger(Pantalla1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ReadOnlyFileException ex) {
                    Logger.getLogger(Pantalla1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvalidAudioFrameException ex) {
                    Logger.getLogger(Pantalla1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> jListCanciones;
    public javax.swing.JList<String> jListRep;
    public javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSlider jVolumen;
    public javax.swing.JLabel lblAgregarLista;
    public javax.swing.JLabel lblAnterior;
    public javax.swing.JLabel lblBorrarCancion;
    public javax.swing.JLabel lblCancionSonando;
    public javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblListRSonando;
    public javax.swing.JLabel lblMinimizar;
    public javax.swing.JLabel lblOrdenarAZ;
    public javax.swing.JLabel lblOrdenarZA;
    public javax.swing.JLabel lblPantalla1;
    public javax.swing.JLabel lblPause;
    public javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblPorVol;
    public javax.swing.JLabel lblRepetir;
    public javax.swing.JLabel lblSeleccionar;
    public javax.swing.JLabel lblSiguiente;
    public javax.swing.JLabel lblStop;
    // End of variables declaration//GEN-END:variables
}
